### ISSUE TITLE
CRITICAL Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by designboxcom** [Coernel82/SEPA-QR-for-Woocommerce#21]
Hello,

I am trying to understand where comes this new error from.
`CRITICAL Uncaught ArgumentCountError: Too few arguments to function muxp_email_after_order_table(), 4 passed in /home/XXXXXX/wp-includes/class-wp-hook.php on line 310 and exactly 5 expected in /home/XXXXXX/wp-content/plugins/mxp-sepaqr/muxp-sepaqr.php:98`
I guess a wrong number of arguments are passed to the function but still I am not really sure where to start from.
Any help / suggestion would be really appreciated. :)

**Comment by Coernel82** [comment]
I am sorry but I am not able to help you. As you can see https://github.com/Coernel82/SEPA-QR-for-Woocommerce/blob/1e24e25fa057f5ce2312d0eff69d03268186022f/mxp-sepaqr/muxp-sepaqr.php#L98C12-L98C12 there are exactly 5 arguments in that line!
Also my emails and pdfs get created correctly! So the plugin itself and hooking it in at least works correctly for me.

I leave this issue open in case someone else has the same problem.

**Comment by petermorlion** [comment]
The funny thing is that [here](https://github.com/Coernel82/SEPA-QR-for-Woocommerce/blob/1e24e25fa057f5ce2312d0eff69d03268186022f/mxp-sepaqr/muxp-sepaqr.php#L107) the code registers an action and tells the system to expect 4, but the function is defined for 5 arguments. Also, extra weird, but it works well on my website as well.
@designboxcom, if you're comfortable with coding, you could try to remove the `$muxp_THANKYOU_EMAIL` parameter in the `muxp_email_after_order_table` function's argument list. It shouldn't be a problem, because the variable is declared in the outer scope at the top of the file.

**Comment by designboxcom** [comment]
Thanks @Coernel82 and @petermorlion .
I did what you suggested and it seems it helped to resolve the error BUT, and this is totally obvious, the extension complains now with another error:
`2023-09-28T12:36:10+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function muxp_create_qrcode(), 2 passed in /home/XXXXX/wp-content/plugins/mxp-sepaqr/muxp-sepaqr.php on line 170 and exactly 3 expected in /home/XXXXX/wp-content/plugins/mxp-sepaqr/muxp-sepaqr.php:188`

When I compare the version, I have te feeling the problems come from the translatable chains. Could it be possible that Loco Translate conflicts with this extension ?

**Comment by petermorlion** [comment]
Ok, found the issue. The reason it worked on my WordPress instance was because I've modified the code. I did it as part of a pull request to store QR codes as images. But to get it to work, I updated the plugin file to match the version you get when you install via the WordPress plugin system. At least, I think that's what I did. And that fixes the issues you're having. 

Did you install it from here or via the plugin system? Because you can see it differs (see https://plugins.svn.wordpress.org/mxp-sepa-qr-code-addon-for-woocommerce/trunk/muxp-sepaqr.php).

Either try that, or download [my fork](https://github.com/petermorlion/SEPA-QR-for-Woocommerce/tree/image-support) (this should be temporary until the PR is merged).

**Comment by citronalco** [comment]
The reason for the error is, that the code on GitHub is not the same as the code in WordPress' SVN, which is used for creating the plugin.
The code on GitHub is buggy, the code in SVN is working.

**Comment by Coernel82** [comment]
I will adress this issue - but unfortunately not this year I guess. I will update the code using the WordPress SVN.

**Comment by Coernel82** [comment]
I overwrote the code here with the working WordPress SVN code!
